<project name="Cascadia" default="jar" basedir=".">
    <property name="src.dir" value="src"/>
    <property name="classes.dir" value="classes"/>
    <property name="jar.dir" value="."/>
    <property name="docs.dir" value="docs/doc"/>
    <property name="jar.name" value="Cascadia.jar"/>

<target name="clean">
    <echo>Cleaning up...</echo>
    <delete includeemptydirs="true">
        <fileset dir="${classes.dir}">
            <include name="**/*"/>
        </fileset>
    </delete>
    <delete>
        <fileset dir="${basedir}/src">
            <include name=".classpath"/>
            <include name=".project"/>
        </fileset>
    </delete>
    <delete dir="${docs.dir}"/>
    <!-- <delete file="${jar.dir}/${jar.name}"/> -->
    <echo>Clean up completed.</echo>
</target>

    <target name="compile" depends="clean">
        <echo>Compiling source files...</echo>
        <mkdir dir="${classes.dir}"/>
        <javac srcdir="${src.dir}" destdir="${classes.dir}" includeantruntime="false">
            <classpath>
                <fileset dir="lib" includes="*.jar"/>
            </classpath>
        </javac>
        <echo>Compilation completed successfully.</echo>
    </target>

    <target name="javadoc" depends="compile">
        <echo>Generating Javadoc...</echo>
        <mkdir dir="${docs.dir}"/>
        <javadoc sourcepath="${src.dir}" destdir="${docs.dir}" use="true" version="true" author="true" charset="UTF-8">
            <doctitle>Cascadia API Documentation</doctitle>
            <bottom>Generated by Apache Ant</bottom>
            <classpath>
                <fileset dir="lib" includes="*.jar"/>
            </classpath>
        </javadoc>
        <echo>Javadoc generated successfully in ${docs.dir}.</echo>
    </target>

    <target name="jar" depends="compile">
        <echo>Building executable JAR file...</echo>
        <mkdir dir="${jar.dir}"/>
        <jar destfile="${jar.dir}/${jar.name}" basedir="${classes.dir}">
            <manifest>
                <attribute name="Main-Class" value="fr.uge.projet.main.Main"/>
		<attribute name="Class-Path" value="lib/zen-6.0.jar lib/zen-6.0-javadoc.jar lib/zen-6.0-sources.jar"/>
            </manifest>
        </jar>
        <echo>Executable JAR file generated: ${jar.dir}/${jar.name}</echo>
    </target>
</project>
